### ISSUE TITLE
PLPlayerKit取消缓存

### ISSUE THREAD

**Issue by DongjieLi** [pili-io/PLPlayerKit#4]
PLPlayerKit可以取消缓存吗，比如：暂停，然后继续播放，会从暂停的地方继续播放.现在应该是这样的吧

**Comment by 0dayZh** [comment]
已添加到 1.2.1-release 的改进中。

**Comment by 0dayZh** [comment]
在初始化时设置参数中的 PLMovieParameterMinBufferedDuration 和 PLMovieParameterMaxBufferedDuration 均为 0 即可。
